### PR TITLE
Rely user validation on Session::init & Check if user has a profile assigned after user creation

### LINKED ISSUE #63: [Bug] "Session expired" error when JIT user creation is enabled and no entity is assigned to the user
When the option **JIT USER CREATION** is enabled in plug-in settings and no GLPI Profile is assigned to the SAML user through the JIT Rules, the message "Session Expired" is shown even with successful SAML user authentication reported in the JIT log (``samlssoevents.log``). 

It would be great if samlSSO could report that the user login fails because no GLPI Profile has been assigned to the User instead of reporting a "Session expired" error, as I've spent the whole afternoon trying to troubleshoot a "Session expired" issue documented on samlSSO wiki that happens because of Docker/reverse proxy (#59), but it wasn't related to it.

Maybe the other authentication types (LDAP, mail) do not fail the same way because the default **Authorizations assignment rules** rule assigns such authentication methods to the **Root entity** by default, but I'm not sure.

Here are the logs:

Documentation: https://glpi-plugins.readthedocs.io/en/latest/saml/entra.html

<details><summary>JIT Rule identical to documentation (fails, "Session expired" error)</summary><pre>
2026-01-09 15:46:20 [@b4539de8f966]
JIT was called with params:array (
  'sub_type' => 'GlpiPlugin\\Samlsso\\RuleSaml',
  'ruleid' => 93,
  'input' => 
  array (
    '_useremails' => 
    array (
      0 => 'eduardo.oliveira@example.com',
    ),
    'samlClaimedGroups' => 
    array (
    ),
    'samlClaimedJobTitle' => false,
    'country' => false,
    'city' => false,
    'street' => false,
  ),
  'output' => 
  array (
    'users_id' => 7,
    '_rule_process' => false,
    'profiles_id' => '1',
    'is_active' => '1',
  ),
)
2026-01-09 15:46:20 [@b4539de8f966]
JIT found no groupId to add.
2026-01-09 15:46:20 [@b4539de8f966]
JIT didnt find a profile for entity assignment. Profile asignment might not work.
2026-01-09 15:46:20 [@b4539de8f966]
JIT didnt find to be assigned profile(s) to be recursive.
2026-01-09 15:46:20 [@b4539de8f966]
JIT remove all existing and default profiles from newly created user:
2026-01-09 15:46:20 [@b4539de8f966]
Done
2026-01-09 15:46:20 [@b4539de8f966]
JIT was not able to assign profile with config:array (
  'users_id' => 7,
  'profiles_id' => '1',
)
</pre></details>

<details><summary>JIT Rule with Recursive parameter set (fails, "Session expired" error)</summary><pre>
```
2026-01-09 18:15:13 [@b4539de8f966]
JIT was called with params:array (
  'sub_type' => 'GlpiPlugin\\Samlsso\\RuleSaml',
  'ruleid' => 93,
  'input' => 
  array (
    '_useremails' => 
    array (
      0 => 'eduardo.oliveira@example.com',
    ),
    'samlClaimedGroups' => 
    array (
    ),
    'samlClaimedJobTitle' => false,
    'country' => false,
    'city' => false,
    'street' => false,
  ),
  'output' => 
  array (
    'users_id' => 9,
    '_rule_process' => false,
    'profiles_id' => '1',
    'is_active' => '1',
    'is_recursive' => '1',
  ),
)
2026-01-09 18:15:13 [@b4539de8f966]
JIT found no groupId to add.
2026-01-09 18:15:13 [@b4539de8f966]
JIT didnt find a profile for entity assignment. Profile asignment might not work.
2026-01-09 18:15:13 [@b4539de8f966]
JIT found to be assigned profile(s) to be recursive.
2026-01-09 18:15:13 [@b4539de8f966]
JIT remove all existing and default profiles from newly created user:
2026-01-09 18:15:13 [@b4539de8f966]
Done
2026-01-09 18:15:13 [@b4539de8f966]
JIT was not able to assign profile with config:array (
  'users_id' => 9,
  'profiles_id' => '1',
  'is_recursive' => '1',
)
</pre></details>

<details><summary>JIT Rule with Recursive + Default Profile (fails, "Session expired" error)</summary><pre>
2026-01-09 18:17:16 [@b4539de8f966]
JIT was called with params:array (
  'sub_type' => 'GlpiPlugin\\Samlsso\\RuleSaml',
  'ruleid' => 92,
  'input' => 
  array (
    '_useremails' => 
    array (
      0 => 'eduardo.oliveira@example.com',
    ),
    'samlClaimedGroups' => 
    array (
    ),
    'samlClaimedJobTitle' => false,
    'country' => false,
    'city' => false,
    'street' => false,
  ),
  'output' => 
  array (
    'users_id' => 10,
    '_rule_process' => false,
    'profiles_id' => '4',
    'is_active' => '1',
    '_profiles_id_default' => '4',
    'is_recursive' => '1',
  ),
)
2026-01-09 18:17:16 [@b4539de8f966]
JIT found no groupId to add.
2026-01-09 18:17:16 [@b4539de8f966]
JIT didnt find a profile for entity assignment. Profile asignment might not work.
2026-01-09 18:17:16 [@b4539de8f966]
JIT found to be assigned profile(s) to be recursive.
2026-01-09 18:17:16 [@b4539de8f966]
JIT remove all existing and default profiles from newly created user:
2026-01-09 18:17:16 [@b4539de8f966]
Done
2026-01-09 18:17:16 [@b4539de8f966]
JIT was not able to assign profile with config:array (
  'users_id' => 10,
  'profiles_id' => '4',
  'is_recursive' => '1',
)
2026-01-09 18:17:16 [@b4539de8f966]
Jit didnt find a default GroupID to assign, skipping
2026-01-09 18:17:16 [@b4539de8f966]
Jit didnt find a default EntityId to assign, skipping
2026-01-09 18:17:16 [@b4539de8f966]
JIT found default profileID:for userId:10
2026-01-09 18:17:16 [@b4539de8f966]
Jit didnt update user defaults
</pre></details>

<details><summary>JIT Rule with Recursive + Default Profile + Entity (fails, "Session expired" error)</summary><pre>
2026-01-09 18:42:36 [@b4539de8f966]
JIT was called with params:array (
  'sub_type' => 'GlpiPlugin\\Samlsso\\RuleSaml',
  'ruleid' => 93,
  'input' => 
  array (
    '_useremails' => 
    array (
      0 => 'eduardo.oliveira@example.com',
    ),
    'samlClaimedGroups' => 
    array (
    ),
    'samlClaimedJobTitle' => false,
    'country' => false,
    'city' => false,
    'street' => false,
  ),
  'output' => 
  array (
    'users_id' => 13,
    '_rule_process' => false,
    'profiles_id' => '1',
    'is_active' => '1',
    'is_recursive' => '1',
  ),
)


2026-01-09 18:42:36 [@b4539de8f966]
JIT found no groupId to add.
2026-01-09 18:42:36 [@b4539de8f966]
JIT didnt find a profile for entity assignment. Profile asignment might not work.
2026-01-09 18:42:36 [@b4539de8f966]
JIT found to be assigned profile(s) to be recursive.
2026-01-09 18:42:36 [@b4539de8f966]
JIT remove all existing and default profiles from newly created user:
2026-01-09 18:42:36 [@b4539de8f966]
Done
2026-01-09 18:42:36 [@b4539de8f966]
JIT was not able to assign profile with config:array (
  'users_id' => 13,
  'profiles_id' => '1',
  'is_recursive' => '1',
)
</pre></details>

<details><summary>JIT Rule with Recursive + Default Profile + Entity + Default Entity (success, no "Session expired" error)</summary><pre>
2026-01-09 19:07:06 [@b4539de8f966]
JIT was called with params:array (
  'sub_type' => 'GlpiPlugin\\Samlsso\\RuleSaml',
  'ruleid' => 93,
  'input' => 
  array (
    '_useremails' => 
    array (
      0 => 'eduardo.oliveira@example.com',
    ),
    'samlClaimedGroups' => 
    array (
    ),
    'samlClaimedJobTitle' => false,
    'country' => false,
    'city' => false,
    'street' => false,
  ),
  'output' => 
  array (
    'users_id' => 14,
    '_rule_process' => false,
    'profiles_id' => '1',
    'is_active' => '1',
    'is_recursive' => '1',
    '_entities_id_default' => '0',
    'entities_id' => '0',
  ),
)
2026-01-09 19:07:06 [@b4539de8f966]
JIT found no groupId to add.
2026-01-09 19:07:06 [@b4539de8f966]
JIT found entity for profile assignment:0
2026-01-09 19:07:06 [@b4539de8f966]
JIT found to be assigned profile(s) to be recursive.
2026-01-09 19:07:06 [@b4539de8f966]
JIT remove all existing and default profiles from newly created user:
2026-01-09 19:07:06 [@b4539de8f966]
Done
2026-01-09 19:07:06 [@b4539de8f966]
JIT assigned profile with config:array (
  'users_id' => 14,
  'profiles_id' => '1',
  'entities_id' => '0',
  'is_recursive' => '1',
)
2026-01-09 19:07:06 [@b4539de8f966]
Jit didnt find a default GroupID to assign, skipping
2026-01-09 19:07:06 [@b4539de8f966]
JIT found default entityID:for userId:14
2026-01-09 19:07:06 [@b4539de8f966]
Jit didnt find a default ProfileId to assign, skipping
2026-01-09 19:07:06 [@b4539de8f966]
Jit didnt update user defaults
</pre></details>

### PR DESCRIPTION
**Pull request by eduardomozart**
Closes https://github.com/DonutsNL/samlsso/issues/63

``Session::init`` already does some basic validations related to the user, like whether it's active, not deleted, and it also supports due dates ("Valid since" and "Valid until" fields on the User page). This PR checks the ``Session::init`` and displays the default GLPI failed login page (the same one displayed for local user errors) if validation fails.

Now the error requests return an HTTP code and log the IP address of the request to make it easier to block requests using Fail2Ban.

### CODE REVIEW

File: src/LoginFlow.php [hunk 1]
```diff
@@ -459,6 +461,18 @@ protected function performGlpiLogin(Response $response, LoginState $state): void
         // This tells GLPI a valid GLPI user was logged in.
         Session::init($auth);
 
+        if (!empty($auth->getErrors())) {
```
Comment (DonutsNL) [inline src/LoginFlow.php]: This validation looks like it should be performed right after the object was initiated @rule:446 or is there a specific reason to wait till after passing it to the Session::init?

**Review by DonutsNL — APPROVED** [review]

File: src/LoginFlow/User.php [hunk 2]
```diff
@@ -174,6 +174,11 @@ public function getOrCreateUser(array $userFields): glpiUser        //Not all pa
                                             reactivate your account.", PLUGIN_NAME));
             }
 
+            // Check if the user has any profiles assigned
```
[the remark this answers is not in the document]
Comment (DonutsNL) [reply src/LoginFlow/User.php]: Possibly need to address the repetition of code and warning messages in the user.php at a later moment. Currently its functional but possibly not required. Removing these repetitions will ease future maintanance and errors. For now its ok.

File: src/LoginFlow.php (hunk 1 above)
Comment (DonutsNL) [reply src/LoginFlow.php:462]: Thats oke, im very happy with the additions you have made thus far. Thank you!
